### ISSUE TITLE
Hi, can you help me in this error I am getting: Cast to ObjectId failed for value "latest" (type string) at path "_id" for model "Product"

### ISSUE THREAD

**Issue by talmax1124** [SAYEED05/macksonic-ecommerce#1]

**Comment by SAYEED05** [comment]
the _id field of the product is not valid objectId.The _id should look like "**507f191e810c19729de860ea**".but more importantly this repo is supposed to be private,i forgot to make it private.i will be making the repo private after this.you can view practically same code in brad's repo as you may have already know.
